In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn import datasets, svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

In [3]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [7]:
#Gaussian Naive Bayes
gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb_pred = gnb.predict(X_test)

In [10]:
print("Acurácia do Naive Bayes: ", accuracy_score(y_test, gnb_pred))
print("Precisão do Naive Bayes: ", precision_score(y_test, gnb_pred, average='weighted'))
print("Recall do Naive Bayes: ", recall_score(y_test, gnb_pred, average='weighted'))
print("F1-Score do Naive Bayes: ", f1_score(y_test, gnb_pred, average='weighted'))
print("---------------------------")
print(classification_report(y_test, gnb_pred))
print("---------------------------")
print(confusion_matrix(y_test, gnb_pred))

Acurácia do Naive Bayes:  0.9333333333333333
Precisão do Naive Bayes:  0.9352007469654529
Recall do Naive Bayes:  0.9333333333333333
F1-Score do Naive Bayes:  0.933615520282187
---------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.89      0.91        18
           2       0.86      0.92      0.89        13

    accuracy                           0.93        45
   macro avg       0.93      0.94      0.93        45
weighted avg       0.94      0.93      0.93        45

---------------------------
[[14  0  0]
 [ 0 16  2]
 [ 0  1 12]]


In [15]:
#Decision Tree Classifier
dt = DecisionTreeClassifier(random_state=0)
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)

In [16]:
print("Accuracy of Decision Tree Classifier: ", accuracy_score(y_test, dt_pred))
print("Precision of Decision Tree Classifier: ", precision_score(y_test, dt_pred, average='weighted'))
print("Recall of Decision Tree Classifier: ", recall_score(y_test, dt_pred, average='weighted'))
print("F1-Score of Decision Tree Classifier: ", f1_score(y_test, dt_pred, average='weighted'))
print("--------------------------------------------")
print(classification_report(y_test, dt_pred))
print("--------------------------------------------")
print(confusion_matrix(y_test, dt_pred))

Accuracy of Decision Tree Classifier:  0.9555555555555556
Precision of Decision Tree Classifier:  0.9555555555555556
Recall of Decision Tree Classifier:  0.9555555555555556
F1-Score of Decision Tree Classifier:  0.9555555555555556
--------------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

--------------------------------------------
[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]


In [22]:
#Support Vector Machine c/ kernel linear
svm_clf = svm.SVC(kernel='linear')
svm_clf.fit(X_train, y_train)
svm_clf_pred = svm_clf.predict(X_test)

In [23]:
print("Accuracy of SVM: ", accuracy_score(y_test, svm_clf_pred))
print("Precision of SVM: ", precision_score(y_test, svm_clf_pred, average='weighted'))
print("Recall of SVM: ", recall_score(y_test, svm_clf_pred, average='weighted'))
print("F1-Score of SVM: ", f1_score(y_test, svm_clf_pred, average='weighted'))
print("--------------------------------------------")
print(classification_report(y_test, svm_clf_pred))
print("--------------------------------------------")
print(confusion_matrix(y_test, svm_clf_pred))

Accuracy of SVM:  1.0
Precision of SVM:  1.0
Recall of SVM:  1.0
F1-Score of SVM:  1.0
--------------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

--------------------------------------------
[[14  0  0]
 [ 0 18  0]
 [ 0  0 13]]
